language: node_js
node_js:
  - 0.12
  - 4
  - 5

before_install:
  - mkdir node_modules; ln -s ../ node_modules/next

notifications:
  email:
    - medikoo+node-ext@medikoo.com

script: "npm test && npm run lint"
